import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const supportedLocales = [
    Locale('id'),
    Locale('en'),
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'id': {
      'appTitle': 'EWS Flood Guard',
      'splashSubtitle': 'Sistem Peringatan Dini Banjir',
      'loginTitle': 'Masuk Platform',
      'loginSubtitle': 'Akses dashboard monitoring banjir real-time.',
      'or': 'ATAU',
      'email': 'EMAIL',
      'password': 'PASSWORD',
      'forgotPassword': 'Lupa Password?',
      'loginButton': 'Masuk',
      'noAccount': 'Belum punya akun?',
      'registerNow': 'Daftar sekarang',
      'registerTitle': 'Daftar Akun Baru',
      'registerSubtitle': 'Lengkapi formulir di bawah untuk bergabung.',
      'fullName': 'NAMA LENGKAP',
      'organization': 'INSTANSI / ORGANISASI',
      'emailHint': 'nama@email.com',
      'passwordHint': 'Minimal 8 karakter',
      'confirmPassword': 'KONFIRMASI PASSWORD',
      'confirmPasswordHint': 'Ulangi password',
      'registerButton': 'Daftar',
      'alreadyHaveAccount': 'Sudah punya akun?',
      'loginHere': 'Login di sini',
      'back': 'Kembali',
      'save': 'Simpan',
      'cancel': 'Batal',
      'ok': 'Oke',
      'close': 'Tutup',
      'alertHistory': 'Riwayat Alert',
      'newAccount': 'Daftar Akun Baru',
      'successRegistrasi': 'Registrasi Berhasil!',
      'agreeTerms': 'Anda harus menyetujui syarat & ketentuan',
      'resetPassword': 'Kirim Link Reset',
      'forgotPasswordTitle': 'Lupa Password?',
      'forgotPasswordSubtitle': 'Masukkan email Anda dan kami akan kirimkan link reset password.',
      'emailAddress': 'Alamat Email',
      'success': 'Berhasil!',
      'returnLogin': 'Kembali ke Login',
      'notificationSettings': 'Pengaturan Notifikasi',
      'floodAlert': 'Alert Banjir',
      'sensorStatusUpdate': 'Update Status Sensor',
      'notificationEmail': 'Notifikasi Email',
      'alertFloodSubtitle': 'Notifikasi ketika status berubah',
      'sensorStatusSubtitle': 'Info pembaruan data sensor',
      'emailNotificationSubtitle': 'Kirim alert ke email terdaftar',
      'accountInfo': 'Informasi Akun',
      'editProfile': 'Edit Profil',
      'profile': 'Profil',
      'user': 'Pengguna',
      'administrator': 'Administrator',
      'notLoggedIn': 'Belum Masuk',
      'loginToAccount': 'Masuk ke akun Anda untuk mengakses profil, riwayat notifikasi, dan pengaturan personal.',
      'loginToAccountButton': 'Masuk ke Akun',
      'registerNewAccount': 'Daftar Akun Baru',
      'accountInfoLabel': 'Informasi Akun',
      'phoneLabel': 'Telepon',
      'institutionLabel': 'Institusi / Instansi',
      'historyAlert': 'Riwayat Alert',
      'historyAlertEmptyTitle': 'Belum ada riwayat alert.',
      'historyAlertEmptyContent': 'Alert akan muncul di sini ketika status banjir berubah.',
      'nearbySensors': 'Sensor Terdekat',
      'nearbySensorsSubtitle': 'Pantau sensor di sekitar Anda',
      'notificationPageTitle': 'Notifikasi Peringatan',
      'markAllRead': 'Tandai semua dibaca',
      'allNotificationsRead': 'Semua notifikasi ditandai sudah dibaca.',
      'noNotifications': 'Belum ada notifikasi',
      'unreadCount': 'Belum dibaca: ',
      'danger': 'Bahaya',
      'warning': 'Waspada',
      'safe': 'Aman',
      'level': 'Tingkat: ',
      'time': 'Waktu: ',
      'detailAlert': 'Detail Peringatan',
      'downloadPdf': 'Unduh PDF',
      'downloadExcel': 'Unduh Excel',
      'reportSummary': 'Ringkasan data sistem',
      'monitoringReport': 'Laporan Monitoring',
      'monitoringReportSubtitle': 'Pilih periode dan unduh rekap data pemantauan banjir.',
      'totalSensors': 'Total Sensor',
      'onlineSensors': 'Sensor Online',
      'warningStatus': 'Status Waspada',
      'dangerStatus': 'Status Bahaya',
      'downloadReportPdf': 'Generate laporan pemantauan dalam format PDF.',
      'downloadReportExcel': 'Ekspor data mentah untuk analisis lanjutan.',
      'noSensorsInstalled': 'Belum ada sensor terpasang. Data sensor akan muncul setelah perangkat IoT aktif.',
      'statusLabel': 'STATUS',
      'waterLevelLabel': 'TINGGI AIR',
      'connectivityLabel': 'KONEKSI',
      'batteryLabel': 'BATERAI',
      'notAvailable': 'Tidak Ada',
      'priorityMonitoringTitle': 'Pantauan Prioritas',
      'priorityMonitoringEmpty': 'Belum ada data sensor yang dapat diprioritaskan saat ini.',
      'sensorUnavailable': 'Belum Tersedia',
      'prioritySensorNote': 'Sensor ini menunjukkan level risiko tertinggi saat ini. Fokuskan perhatian Anda di area ini.',
      'sensorMapTitle': 'Peta Sensor',
      'liveChartTitle': 'Grafik Telemetri Historis',
      'waitingForData': 'Menunggu Data Masuk...',
      'sensorWillStreamData': 'Sensor akan memancarkan telemetri secara real-time.',
      'liveSupabase': 'Live Supabase',
      'actionPanelTitle': 'Aksi Darurat & Pintasan',
      'actionPanelSubtitle': 'Akses cepat menu penting.',
      'openSensorMap': 'Buka Peta Sensor',
      'mitigationGuide': 'Panduan Mitigasi',
      'safetyFirst': 'Keselamatan jiwa\ndahulu.',
      'rawDataTable': 'Tabel Data Mentah',
      'waterLevelGraphTitle': 'Grafik Tinggi Air',
      'rainfallGraphTitle': 'Grafik Curah Hujan',
      'flowRateGraphTitle': 'Grafik Debit Aliran',
      'downloadSuccess': 'Unduh berhasil. File tersimpan di:',
      'failedLoadHistory': 'Gagal memuat data riwayat.',
      'day': 'Hari',
      'week': 'Minggu',
      'minimum': 'MINIMUM',
      'average': 'RATA-RATA',
      'current': 'SAAT INI',
      'beforeCallingTip1': 'Sebutkan lokasi detail (alamat, patokan terdekat, atau titik Google Maps).',
      'beforeCallingTip2': 'Jelaskan kondisi saat ini: tinggi air, arus, akses jalan, dan cuaca.',
      'beforeCallingTip3': 'Informasikan jumlah warga terdampak dan kelompok rentan (anak/lansia/disabilitas).',
      'beforeCallingTip4': 'Sampaikan kebutuhan paling mendesak: evakuasi, medis, logistik, atau penyelamatan.',
      'dateRangeSearchLabel': 'Rentang Tanggal Pencarian',
      'allSensors': 'Semua Sensor',
      'sensorLabel': 'Sensor',
      'showData': 'Tampilkan Data',
      'processing': 'Memproses...',
      'waterLevelCm': 'Ketinggian (cm)',
      'rainfallMm': 'Hujan (mm)',
      'flowRateLpm': 'Debit (LPM)',
      'monitorOnDashboard': 'Pantau di Dasbor',
      'monitorStatus': 'STATUS PEMANTAUAN',
      'sensorMapList': 'Peta & Daftar Sensor',
      'sensorMapDescription': 'Identifikasi titik risiko banjir secara real-time melalui integrasi peta and data metrik sensor.',
      'sensorOffline': 'Sensor Offline',
      'overallStatusTitle': 'STATUS KESELURUHAN WILAYAH',
      'noSensorStatusAvailable': 'TIDAK TERSEDIA',
      'noSensorStatusSubtitle': 'Belum ada sensor terpasang. Silakan pasang perangkat IoT terlebih dahulu untuk melihat data real-time.',
      'sensorMonitorTitle': 'Monitor Sensor Spesifik',
      'sensorMonitorSubtitle': 'Pilih area untuk melihat detail metrik.',
      'activeWaterLevel': 'Tinggi Air (Aktif)',
      'currentPeak': 'Puncak saat ini',
      'rainfallLight': 'Ringan',
      'rainfallModerate': 'Sedang',
      'riskSensors': 'Sensor Berisiko',
      'sensorOnlineActive': 'Sensor online aktif',
      'noSensorsAvailable': 'Tidak ada sensor',
      'recommendedActionsTitle': 'Tindakan yang Disarankan',
      'actionDescWarning': 'Air mulai naik. Siap-siap tanpa panik.',
      'actionDescAlert': 'Risiko banjir makin tinggi. Fokus ke pra-evakuasi.',
      'actionDescDanger': 'Kondisi kritis. Prioritas utama adalah menyelamatkan jiwa.',
      'actionDescNormal': 'Situasi saat ini aman. Tetap pantau dashboard secara berkala.',
      'actionPointWarning1': 'Pantau dashboard tiap 10-15 menit.',
      'actionPointWarning2': 'Siapkan tas siaga.',
      'actionPointWarning3': 'Pastikan rute evakuasi keluarga.',
      'actionPointAlert1': 'Pindahkan barang berharga ke tempat tinggi.',
      'actionPointAlert2': 'Siapkan kelompok rentan untuk berangkat lebih awal.',
      'actionPointAlert3': 'Pastikan jalur evakuasi tidak terhalang.',
      'actionPointDanger1': 'Evakuasi segera ke lokasi aman resmi.',
      'actionPointDanger2': 'Hubungi layanan darurat jika ada yang terjebak.',
      'actionPointDanger3': 'Ikuti instruksi petugas.',
      'actionPointNormal1': 'Pantau pembaruan level air setiap 30 menit.',
      'actionPointNormal2': 'Pastikan notifikasi perangkat tetap aktif.',
      'actionPointNormal3': 'Simpan jalur evakuasi sebagai antisipasi.',
      'floodPreparednessGuideTitle': 'Panduan Kesiapsiagaan Banjir',
      'floodPreparednessGuideSubtitle': 'Pelajari langkah cepat saat mendapatkan peringatan: cek status, siapkan barang penting, dan prioritaskan evakuasi.',
      'guideStepWarningLabel': 'Kuning (Waspada)',
      'guideStepWarningDesc': 'Pantau kondisi dan siapkan tas siaga dengan dokumen, obat, dan makanan.',
      'guideStepAlertLabel': 'Oren (Siaga)',
      'guideStepAlertDesc': 'Amankan barang berharga ke tempat tinggi dan siapkan jalur evakuasi.',
      'guideStepDangerLabel': 'Merah (Bahaya)',
      'guideStepDangerDesc': 'Evakuasi segera ke lokasi aman resmi dan bantu keluarga keluar lebih dulu.',
      'flowHighLabel': 'Debit Tinggi',
      'flowMediumLabel': 'Debit Sedang',
      'flowLowLabel': 'Debit Rendah',
      'noWaterLevelData': 'Belum ada data ketinggian air yang masuk untuk sensor ini.',
      'noRainfallData': 'Belum ada data curah hujan yang masuk untuk sensor ini.',
      'noFlowRateData': 'Belum ada data debit air yang masuk untuk sensor ini.',
      'lastUpdate': 'Pembaruan Terakhir',
      'globalStatus': 'Status Global: ',
      'interactiveSensorMap': 'Peta Interaktif Sensor',
      'noSensorsFromBackend': 'Belum ada sensor dari backend.',
      'focusDetails': 'DETAIL FOKUS',
      'selectPointOnMap': 'Pilih titik di peta.',
      'searchSensorHint': 'Cari sensor...',
      'allFilter': 'Semua',
      'normalFilter': 'Normal',
      'warningFilter': 'Waspada',
      'dangerFilter': 'Bahaya',
      'sensorNotFound': 'Sensor tidak ditemukan.',
      'offlineFallbackMessage': 'Tidak dapat menjangkau server. Menampilkan data cadangan. Tarik ke bawah untuk memuat ulang.',
      'priorityEmergencyServices': 'Layanan Darurat Prioritas',
      'emergencyActionSubtitle': 'Tekan tombol panggil sesuai kebutuhan utama yang sedang terjadi.',
      'emergencyContactsTitle': 'Kontak Darurat',
      'emergencyContactsSubtitle': 'Gunakan halaman ini saat situasi kritis. Pilih layanan yang tepat dan sampaikan informasi yang jelas agar bantuan datang lebih cepat.',
      'dangerPriorityTag': 'Prioritas saat\nstatus Bahaya',
      'callPreparationTitle': 'Informasi yang Harus Disiapkan Saat Menelepon',
      'callPreparationSubtitle': 'Semakin jelas informasi yang kamu sampaikan, semakin cepat tim dapat menentukan tindakan.',
      'quickActionFlowTitle': 'Alur Tindakan Cepat',
      'quickActionStep1': 'Cek sensor paling berisiko di Dashboard/Peta.',
      'quickActionStep2': 'Hubungi layanan darurat yang paling relevan.',
      'quickActionStep3': 'Ikuti arahan petugas dan prioritaskan evakuasi aman.',
      'emergencyNumberLabel': 'Nomor Darurat',
      'serviceFocusLabel': 'Fokus layanan',
      'responseEstimateLabel': 'Estimasi respons',
      'callContactTitle': 'Hubungi {name}',
      'callContactPrompt': 'Apakah Anda ingin menghubungi {phone}?',
      'callContactButton': 'Hubungi {phone}',
      'latLngLabel': 'Lat/Lng:',
      'rainfallLabel': 'CURAH HUJAN',
      'flowRateLabel': 'DEBIT AIR',
      'retry': 'Coba Lagi',
      'alertHeaderTitle': 'Notifikasi & Alert',
      'alertHeaderSubtitle': 'Pantau notifikasi banjir dan update sistem',
      'noActiveAlerts': 'Belum ada alert aktif',
      'markReadFailed': 'Gagal menandai notifikasi sebagai dibaca.',
      'downloadingReport': 'Mengunduh',
      'exportFailed': 'Export gagal:',
      'normal': 'Normal',
      'offline': 'Offline',
      'openDashboard': 'Buka Dashboard',
      'checkNotifications': 'Cek Notifikasi',
      'viewSensorMap': 'Lihat Peta Sensor',
      'emergencyContacts': 'Kontak Darurat',
      'emailRequired': 'Email wajib diisi',
      'passwordRequired': 'Password wajib diisi',
      'emailInvalid': 'Email tidak valid',
      'passwordShort': 'Password terlalu pendek',
      'passwordMismatch': 'Password tidak cocok',
      'languageSettings': 'Pengaturan Bahasa',
      'indonesian': 'Bahasa Indonesia',
      'english': 'English',
      'helpFAQ': 'Bantuan & FAQ',
      'privacyPolicy': 'Kebijakan Privasi',
      'aboutApp': 'Tentang Aplikasi',
      'aboutAppDescription': 'Sistem Peringatan Dini Banjir berbasis sensor IoT untuk wilayah Batang Arau, Padang, Sumatera Barat.',
      'logoutAccount': 'Keluar dari Akun',
      'copyrightInfo': '© 2026 EWS Flood Guard. Semua hak dilindungi.',
      'saveChanges': 'Simpan Perubahan',
      'profileUpdated': 'Profil berhasil diperbarui',
      'logoutDialogTitle': 'Keluar dari Akun?',
      'logoutDialogContent': 'Apakah Anda yakin ingin keluar? Anda perlu login kembali untuk mengakses fitur personal.',
      'yesLogout': 'Ya, Keluar',
      'loggedOutSuccess': 'Berhasil keluar dari akun',
      'loginWithGoogle': 'Daftar dengan Google',
      'registerWithGoogle': 'Registrasi & Login dengan Google Berhasil!',
      'googleSignUpFailed': 'Google sign-up gagal',
      'dashboard': 'Dasbor',
      'sensors': 'Sensor',
      'alertsMenu': 'Peringatan',
      'reports': 'Laporan',
      'appVersionInfo': 'Versi 1.0.0 • EWS Flood Guard',
      'more': 'Lainnya',
      'sensorActive': 'Sensor Aktif',
      'appSubtitle': 'Early Warning System',
      'adminDashboardTitle': 'Dasbor Admin',
      'adminSearchHint': 'Cari sensor, notifikasi, atau laporan...',
      'welcomeMessage': 'Selamat Datang! ',
      'adminDashboardSubtitle': 'Ringkasan cepat kondisi sistem Early Warning System untuk membantu tim merespons perubahan level air lebih sigap.',
      'dashboardYearTag': '2026/2027',
      'sensorsInAlertStatus': 'Sensor dalam status alert',
      'systemMonitoredSafe': 'Sistem terpantau aman',
      'needsImmediateResponse': 'Perlu respons segera',
      'noThreats': 'Tidak ada ancaman',
      'averageSensorData': 'Rata-rata data sensor',
      'peakWaterLevel': 'Puncak Tinggi Air',
      'highestReading': 'Pembacaan tertinggi',
      'needsDeviceCheck': 'Perlu pengecekan alat',
      'allSensorsOnline': 'Semua sensor online',
      'emailPasswordRequired': 'Email dan password tidak boleh kosong',
      'notAdminError': 'Anda bukan admin',
      'loginFailed': 'Login gagal',
      'adminLoginTitle': 'Login Admin',
      'manualAlertBroadcast': 'Siarkan Peringatan Manual (Broadcast)',
      'alertLevelLabel': 'Tingkat Bahaya',
      'alertTitle': 'Judul Peringatan',
      'titleRequired': 'Judul wajib diisi',
      'alertMessage': 'Pesan Peringatan',
      'messageRequired': 'Pesan wajib diisi',
      'alertDefaultTitle': 'Peringatan Kenaikan Debit Air',
      'alertDefaultMessage': 'Peringatan: Kenaikan volume air terdeteksi di pintu air hulu.',
      'sendPushNotification': 'Kirim via Push Notification',
      'sendEmail': 'Kirim via Email',
      'chooseChannelWarning': 'Pilih minimal satu saluran (Push/Email)',
      'alertBroadcastSuccess': 'Peringatan berhasil disiarkan',
      'alertBroadcastFailed': 'Gagal mengirim peringatan',
      'broadcastHistoryTitle': 'Riwayat Broadcast Kebencanaan',
      'noBroadcastHistory': 'Belum ada riwayat broadcast.',
      'broadcastNow': 'Siarkan Sekarang',
      'adminUsersTitle': 'Manajemen Pengguna',
      'deleteUserTitle': 'Hapus Pengguna',
      'deleteUserConfirm': 'Apakah Anda yakin ingin menghapus pengguna "{name}"?',
      'deleteUserAction': 'Hapus',
      'deletingUser': 'Menghapus pengguna...',
      'userDeletedSuccess': 'Pengguna berhasil dihapus.',
      'userDeletedFailed': 'Gagal menghapus pengguna.',
      'addUserTitle': 'Tambah Pengguna',
      'addUserButton': 'Tambah Pengguna',
      'editUserTitle': 'Edit Pengguna',
      'createUserSuccess': 'Pengguna baru berhasil ditambahkan.',
      'createUserFailed': 'Gagal membuat pengguna.',
      'userUpdatedSuccess': 'Pengguna berhasil diperbarui.',
      'userUpdateFailed': 'Gagal memperbarui pengguna.',
      'nameLabel': 'Nama',
      'emailLabel': 'Email',
      'passwordLabel': 'Password',
      'whatsappNumberLabel': 'No. WA',
      'roleLabel': 'Role',
      'adminRole': 'Admin',
      'userRole': 'User',
      'nameRequired': 'Nama wajib diisi.',
      'noUsersFromBackend': 'Belum ada data pengguna dari backend.',
      'roleAdmin': 'Role Admin',
      'roleUser': 'Role User',
      'userManagementTitle': 'Manajemen Pengguna',
      'totalAccounts': 'Total Akun',
      'userListSubtitle': 'Daftar Akun Otorisasi Sistem',
      'logoutAppTitle': 'Keluar Aplikasi',
      'logoutAppContent': 'Apakah Anda yakin ingin keluar dari aplikasi?',
      'deleteSensorTitle': 'Hapus sensor',
      'deleteSensorConfirm': 'Apakah Anda yakin ingin menghapus sensor ini? Tindakan ini tidak dapat dibatalkan.',
      'deleteSensorAction': 'Hapus',
      'deleteSensorSuccess': 'Sensor berhasil dihapus',
      'deleteSensorFailed': 'Gagal menghapus sensor',
      'editSensorTitle': 'Edit Sensor',
      'saveSensor': 'Simpan',
      'sensorIdLabel': 'ID Perangkat (sensorId)',
      'sensorLocationLabel': 'Nama Lokasi',
      'sensorTypeLabel': 'Tipe Sensor',
      'sensorTypeWaterLevel': 'Water Level (Tinggi Air)',
      'sensorTypeRainfall': 'Rainfall (Curah Hujan)',
      'sensorTypeFlowRate': 'Flow Rate (Debit Aliran)',
      'sensorTypeRainGauge': 'Rain Gauge',
      'sensorConnectivityLabel': 'Status Koneksi',
      'sensorOnline': 'Online',
      'latitudeLabel': 'Latitude',
      'longitudeLabel': 'Longitude',
      'addSensorTitle': 'Tambah Sensor Baru',
      'addSensorButton': 'Tambah',
      'sensorIdHint': 'contoh: SNS-WL-04',
      'sensorCreateRequired': 'ID Perangkat dan Nama Lokasi wajib diisi',
      'sensorCreatedSuccess': 'Sensor baru berhasil ditambahkan',
      'sensorCreatedFailed': 'Gagal menambahkan sensor',
      'sensorUpdatedSuccess': 'Sensor berhasil diperbarui',
      'sensorUpdatedFailed': 'Gagal memperbarui sensor',
      'sensorUnnamed': 'Sensor Tanpa Nama',
      'sensorDetailsIdLabel': 'ID Sensor',
      'noSensorsInstalledAdmin': 'Belum ada sensor terpasang. Silakan tambahkan perangkat IoT terlebih dahulu agar data sensor dapat muncul di halaman ini.',
      'noSensorsInstalledAdminTitle': 'Belum ada sensor terpasang.',
      'noSensorsInstalledAdminSubtitle': 'Silakan tambahkan perangkat IoT terlebih dahulu agar data sensor dapat muncul di halaman ini.',
      'thresholdWaterLevelTitle': 'Konfigurasi Batas Tinggi Air (Ultrasonic)',
      'thresholdRainfallTitle': 'Konfigurasi Batas Intensitas Curah Hujan',
      'thresholdNormalMaxLabel': 'Level Normal Maksimal (cm)',
      'thresholdWarningMinLabel': 'Level Waspada Minimal (cm)',
      'thresholdWarningMaxLabel': 'Level Waspada Maksimal (cm)',
      'thresholdDangerMinLabel': 'Level Bahaya Minimal (cm)',
      'thresholdRainLightMaxLabel': 'Hujan Ringan Maksimal (mm/jam)',
      'thresholdRainModerateMaxLabel': 'Hujan Sedang Maksimal (mm/jam)',
      'thresholdRainHeavyMinLabel': 'Hujan Lebat Minimal (mm/jam)',
      'thresholdUpdateSuccess': 'Konfigurasi ambang batas berhasil diperbarui!',
      'thresholdUpdateFailed': 'Gagal menyimpan konfigurasi.',
      'fieldRequired': 'Nilai wajib diisi',
      'numberInvalid': 'Masukkan angka yang valid',
      'recordsFound': '{count} record ditemukan',
      'noDataLogsInRange': 'Tidak ada data logs pada rentang filter ini.',
      'noFilteredData': 'Tidak ada data terfilter.',
      'reportChartWaterTitle': 'Grafik Tinggi Air',
      'reportChartRainTitle': 'Grafik Curah Hujan',
      'reportChartFlowTitle': 'Grafik Debit Aliran',
      'latestValueLabel': 'Terkini',
      'reportStatMin': 'MIN',
      'reportStatAverage': 'RATA-RATA',
      'reportStatLatest': 'TERKINI',
      'tableTimeLabel': 'Waktu',
      'tableSensorLabel': 'Sensor',
      'tableHeightLabel': 'Ketinggian (cm)',
      'tableRainLabel': 'Hujan (mm)',
      'tableFlowLabel': 'Debit (LPM)',
      'sensorTypeWaterLevelShort': 'Water Level',
      'sensorTypeRainGaugeShort': 'Rain Gauge',
      'sensorTypeLabelShort': 'Tipe',
      'sensorCoordinatesLabel': 'Koordinat',
      'batteryLabelShort': 'Baterai',
      'adminDashboardLoadFailed': 'Gagal memuat dasbor admin: {error}',
      'alertDangerTag': 'Bahaya',
      'alertWarningTag': 'Waspada',
      'alertSafeTag': 'Aman',
      'deviceTypeLabel': 'Tipe Perangkat',
      'adminMapDescription': 'Identifikasi titik risiko banjir secara real-time melalui integrasi peta dan data metrik sensor.',
      'selectSensorLabel': 'Pilih Sensor',
      'users': 'Pengguna',
    },
    'en': {
      'appTitle': 'EWS Flood Guard',
      'splashSubtitle': 'Flood Early Warning System',
      'loginTitle': 'Sign in',
      'loginSubtitle': 'Access real-time flood monitoring dashboard.',
      'or': 'OR',
      'email': 'EMAIL',
      'password': 'PASSWORD',
      'forgotPassword': 'Forgot Password?',
      'loginButton': 'Sign In',
      'noAccount': 'Don\'t have an account?',
      'registerNow': 'Register now',
      'registerTitle': 'Create New Account',
      'registerSubtitle': 'Complete the form below to join.',
      'fullName': 'FULL NAME',
      'organization': 'ORGANIZATION / INSTITUTION',
      'emailHint': 'name@email.com',
      'passwordHint': 'At least 8 characters',
      'confirmPassword': 'CONFIRM PASSWORD',
      'confirmPasswordHint': 'Repeat password',
      'registerButton': 'Sign Up',
      'alreadyHaveAccount': 'Already have an account?',
      'loginHere': 'Login here',
      'back': 'Back',
      'save': 'Save',
      'cancel': 'Cancel',
      'ok': 'OK',
      'close': 'Close',
      'alertHistory': 'Alert History',
      'newAccount': 'Create New Account',
      'successRegistrasi': 'Registration Successful!',
      'agreeTerms': 'You must agree to the terms & conditions',
      'resetPassword': 'Send Reset Link',
      'forgotPasswordTitle': 'Forgot Password?',
      'forgotPasswordSubtitle': 'Enter your email and we will send a reset link.',
      'emailAddress': 'Email Address',
      'success': 'Success!',
      'returnLogin': 'Back to Login',
      'notificationSettings': 'Notification Settings',
      'floodAlert': 'Flood Alert',
      'sensorStatusUpdate': 'Sensor Status Update',
      'notificationEmail': 'Email Notifications',
      'alertFloodSubtitle': 'Notify when status changes',
      'sensorStatusSubtitle': 'Sensor data update info',
      'emailNotificationSubtitle': 'Send alerts to registered email',
      'accountInfo': 'Account Information',
      'editProfile': 'Edit Profile',
      'profile': 'Profile',
      'user': 'User',
      'administrator': 'Administrator',
      'notLoggedIn': 'Not Signed In',
      'loginToAccount': 'Sign in to access profile, notification history, and personal settings.',
      'loginToAccountButton': 'Sign In',
      'registerNewAccount': 'Register New Account',
      'accountInfoLabel': 'Account Information',
      'phoneLabel': 'Phone',
      'institutionLabel': 'Institution / Organization',
      'historyAlert': 'Alert History',
      'historyAlertEmptyTitle': 'No alert history yet.',
      'historyAlertEmptyContent': 'Alerts will appear here when flood status changes.',
      'nearbySensors': 'Nearby Sensors',
      'nearbySensorsSubtitle': 'Monitor nearby sensors',
      'notificationPageTitle': 'Early Warning Notifications',
      'markAllRead': 'Mark all as read',
      'allNotificationsRead': 'All notifications marked as read.',
      'noNotifications': 'No notifications yet',
      'unreadCount': 'Unread: ',
      'danger': 'Danger',
      'warning': 'Warning',
      'alert': 'Alert',
      'safe': 'Safe',
      'level': 'Level: ',
      'time': 'Time: ',
      'detailAlert': 'Alert Details',
      'downloadPdf': 'Download PDF',
      'downloadExcel': 'Download Excel',
      'reportSummary': 'System data summary',
      'monitoringReport': 'Monitoring Report',
      'monitoringReportSubtitle': 'Choose a period and download flood monitoring recap data.',
      'totalSensors': 'Total Sensors',
      'onlineSensors': 'Sensors Online',
      'warningStatus': 'Warning Status',
      'dangerStatus': 'Danger Status',
      'downloadReportPdf': 'Generate monitoring report in PDF format.',
      'downloadReportExcel': 'Export raw data for further analysis.',
      'noSensorsInstalled': 'No sensors installed. Sensor data will appear once IoT devices are active.',
      'statusLabel': 'STATUS',
      'waterLevelLabel': 'WATER LEVEL',
      'connectivityLabel': 'CONNECTIVITY',
      'batteryLabel': 'BATTERY',
      'notAvailable': 'Not Available',
      'liveChartTitle': 'Historical Telemetry Chart',
      'waitingForData': 'Waiting for data...',
      'sensorWillStreamData': 'Sensor will stream telemetry in real-time.',
      'liveSupabase': 'Live Supabase',
      'actionPanelTitle': 'Emergency Actions & Shortcuts',
      'actionPanelSubtitle': 'Quick access to important menus.',
      'openSensorMap': 'Open Sensor Map',
      'mitigationGuide': 'Mitigation Guide',
      'safetyFirst': 'Safety first.',
      'rawDataTable': 'Raw Data Table',
      'waterLevelGraphTitle': 'Water Level Chart',
      'rainfallGraphTitle': 'Rainfall Chart',
      'flowRateGraphTitle': 'Flow Rate Chart',
      'downloadSuccess': 'Download successful. File saved at:',
      'failedLoadHistory': 'Failed to load history data.',
      'day': 'Day',
      'week': 'Week',
      'minimum': 'MINIMUM',
      'average': 'AVERAGE',
      'current': 'CURRENT',
      'beforeCallingTip1': 'Provide a detailed location (address, nearby landmark, or Google Maps pin).',
      'beforeCallingTip2': 'Describe the current conditions: water level, flow, road access, and weather.',
      'beforeCallingTip3': 'Report the number of affected people and vulnerable groups (children/elderly/disabled).',
      'beforeCallingTip4': 'State the most urgent needs: evacuation, medical, logistics, or rescue.',
      'dateRangeSearchLabel': 'Date range for search',
      'allSensors': 'All Sensors',
      'sensorLabel': 'Sensor',
      'showData': 'Show Data',
      'waterLevelCm': 'Water Level (cm)',
      'rainfallMm': 'Rainfall (mm)',
      'flowRateLpm': 'Flow Rate (LPM)',
      'monitorOnDashboard': 'Monitor on Dashboard',
      'monitorStatus': 'MONITORING STATUS',
      'sensorMapList': 'Sensor Map & List',
      'sensorMapDescription': 'Identify flood risk points in real-time through map and sensor metric data integration.',
      'noSensorStatusAvailable': 'NOT AVAILABLE',
      'noSensorStatusSubtitle': 'No sensors installed. Please install IoT devices first to view real-time data.',
      'sensorMonitorTitle': 'Specific Sensor Monitor',
      'sensorMonitorSubtitle': 'Select an area to view metric details.',
      'activeWaterLevel': 'Active Water Level',
      'currentPeak': 'Current peak',
      'rainfallLight': 'Light',
      'rainfallModerate': 'Moderate',
      'riskSensors': 'At-Risk Sensors',
      'sensorOnlineActive': 'Active online sensors',
      'noSensorsAvailable': 'No sensors available',
      'recommendedActionsTitle': 'Recommended Actions',
      'actionDescWarning': 'Water is rising. Stay ready without panicking.',
      'actionDescAlert': 'Flood risk is increasing. Focus on pre-evacuation.',
      'actionDescDanger': 'Conditions are critical. Saving lives is the top priority.',
      'actionDescNormal': 'Current conditions are safe. Continue monitoring the dashboard regularly.',
      'actionPointWarning1': 'Check the dashboard every 10-15 minutes.',
      'actionPointWarning2': 'Prepare an emergency bag.',
      'actionPointWarning3': 'Secure evacuation routes for your family.',
      'actionPointAlert1': 'Move valuables to higher ground.',
      'actionPointAlert2': 'Prepare vulnerable groups to depart early.',
      'actionPointAlert3': 'Ensure evacuation routes are clear.',
      'actionPointDanger1': 'Evacuate immediately to an official safe location.',
      'actionPointDanger2': 'Call emergency services if someone is trapped.',
      'actionPointDanger3': 'Follow the instructions of authorities.',
      'actionPointNormal1': 'Monitor water level updates every 30 minutes.',
      'actionPointNormal2': 'Keep device notifications enabled.',
      'actionPointNormal3': 'Save evacuation routes as a precaution.',
      'floodPreparednessGuideTitle': 'Flood Preparedness Guide',
      'floodPreparednessGuideSubtitle': 'Learn quick steps when alerts arrive: check status, prepare essentials, and prioritize evacuation.',
      'guideStepWarningLabel': 'Yellow (Warning)',
      'guideStepWarningDesc': 'Monitor conditions and prepare a readiness bag with documents, medicine, and food.',
      'guideStepAlertLabel': 'Orange (Alert)',
      'guideStepAlertDesc': 'Secure valuables in high places and ready evacuation routes.',
      'guideStepDangerLabel': 'Red (Danger)',
      'guideStepDangerDesc': 'Evacuate immediately to a safe official location and help your family leave first.',
      'flowHighLabel': 'High Flow',
      'flowMediumLabel': 'Medium Flow',
      'flowLowLabel': 'Low Flow',
      'noWaterLevelData': 'No water level data has arrived for this sensor.',
      'noRainfallData': 'No rainfall data has arrived for this sensor.',
      'noFlowRateData': 'No flow rate data has arrived for this sensor.',
      'lastUpdate': 'Last Update',
      'offlineFallbackMessage': 'Unable to reach server. Showing cached data. Pull down to reload.',
      'priorityEmergencyServices': 'Priority Emergency Services',
      'emergencyActionSubtitle': 'Tap the call button for the most relevant urgent need.',
      'emergencyContactsTitle': 'Emergency Contacts',
      'emergencyContactsSubtitle': 'Use this page in critical situations. Choose the right service and share clear details for faster help.',
      'dangerPriorityTag': 'Priority during\nDanger status',
      'callPreparationTitle': 'Information to Prepare Before Calling',
      'callPreparationSubtitle': 'The clearer your information, the faster the team can decide on action.',
      'quickActionFlowTitle': 'Quick Action Flow',
      'quickActionStep1': 'Check the highest-risk sensors on the Dashboard/Map.',
      'quickActionStep2': 'Call the most relevant emergency service.',
      'quickActionStep3': 'Follow officer directions and prioritize safe evacuation.',
      'emergencyNumberLabel': 'Emergency Number',
      'serviceFocusLabel': 'Service Focus',
      'responseEstimateLabel': 'Estimated Response',
      'callContactTitle': 'Call {name}',
      'callContactPrompt': 'Do you want to call {phone}?',
      'callContactButton': 'Call {phone}',
      'latLngLabel': 'Lat/Lng:',
      'rainfallLabel': 'RAINFALL',
      'flowRateLabel': 'FLOW RATE',
      'idLabel': 'ID:',
      'globalStatus': 'Global Status: ',
      'interactiveSensorMap': 'Interactive Sensor Map',
      'noSensorsFromBackend': 'No sensors available from backend.',
      'focusDetails': 'FOCUS DETAILS',
      'selectPointOnMap': 'Select a point on the map.',
      'searchSensorHint': 'Search sensor...',
      'allFilter': 'All',
      'normalFilter': 'Normal',
      'warningFilter': 'Warning',
      'dangerFilter': 'Danger',
      'sensorNotFound': 'No sensor found.',
      'errorLoadAlerts': 'Failed to load latest alerts:',
      'retry': 'Retry',
      'alertHeaderTitle': 'Notifications & Alerts',
      'alertHeaderSubtitle': 'Monitor flood notifications and system updates',
      'noActiveAlerts': 'No active alerts yet',
      'markReadFailed': 'Failed to mark notifications as read.',
      'downloadingReport': 'Downloading',
      'exportFailed': 'Export failed:',
      'normal': 'Normal',
      'offline': 'Offline',
      'openDashboard': 'Open Dashboard',
      'checkNotifications': 'Check Notifications',
      'viewSensorMap': 'View Sensor Map',
      'emergencyContacts': 'Emergency Contacts',
      'emailRequired': 'Email is required',
      'passwordRequired': 'Password is required',
      'emailInvalid': 'Email is invalid',
      'passwordShort': 'Password is too short',
      'passwordMismatch': 'Passwords do not match',
      'languageSettings': 'Language Settings',
      'indonesian': 'Indonesian',
      'english': 'English',
      'helpFAQ': 'Help & FAQ',
      'privacyPolicy': 'Privacy Policy',
      'aboutApp': 'About App',
      'aboutAppDescription': 'Flood Early Warning System based on IoT sensors for Batang Arau, Padang, West Sumatra.',
      'logoutAccount': 'Logout',
      'copyrightInfo': '© 2026 EWS Flood Guard. All rights reserved.',
      'saveChanges': 'Save Changes',
      'profileUpdated': 'Profile updated successfully',
      'logoutDialogTitle': 'Logout?',
      'logoutDialogContent': 'Are you sure you want to logout? You will need to sign in again to access personal features.',
      'yesLogout': 'Yes, Logout',
      'loggedOutSuccess': 'Logged out successfully',
      'loginWithGoogle': 'Sign in with Google',
      'registerWithGoogle': 'Registration & Google login successful!',
      'googleSignUpFailed': 'Google sign-up failed',
      'dashboard': 'Dashboard',
      'sensors': 'Sensors',
      'alertsMenu': 'Alerts',
      'reports': 'Reports',
      'appVersionInfo': 'Version 1.0.0 • EWS Flood Guard',
      'more': 'More',
      'sensorActive': 'Active Sensors',
      'appSubtitle': 'Early Warning System',
      'adminDashboardTitle': 'Admin Dashboard',
      'adminSearchHint': 'Search sensors, notifications, or reports...',
      'welcomeMessage': 'Welcome! ',
      'adminDashboardSubtitle': 'A quick overview of the Early Warning System to help your team respond faster to rising water levels.',
      'dashboardYearTag': '2026/2027',
      'sensorsInAlertStatus': 'Sensors in alert status',
      'systemMonitoredSafe': 'System is monitored and safe',
      'needsImmediateResponse': 'Needs immediate response',
      'noThreats': 'No threats detected',
      'averageSensorData': 'Average sensor data',
      'peakWaterLevel': 'Peak water level',
      'highestReading': 'Highest reading',
      'needsDeviceCheck': 'Needs device check',
      'allSensorsOnline': 'All sensors online',
      'emailPasswordRequired': 'Email and password cannot be empty',
      'notAdminError': 'You are not an admin',
      'loginFailed': 'Login failed',
      'adminLoginTitle': 'Admin Login',
      'manualAlertBroadcast': 'Broadcast manual alert',
      'alertLevelLabel': 'Severity Level',
      'alertTitle': 'Alert Title',
      'titleRequired': 'Title is required',
      'alertMessage': 'Alert Message',
      'messageRequired': 'Message is required',
      'alertDefaultTitle': 'Flood Alert: Rising Water Level',
      'alertDefaultMessage': 'Alert: Rising water discharge detected upstream. Please monitor and prepare response teams.',
      'sendPushNotification': 'Send via Push Notification',
      'sendEmail': 'Send via Email',
      'chooseChannelWarning': 'Select at least one channel (Push/Email)',
      'alertBroadcastSuccess': 'Alert broadcast successfully',
      'alertBroadcastFailed': 'Failed to send alert',
      'broadcastHistoryTitle': 'Disaster Broadcast History',
      'noBroadcastHistory': 'No broadcast history yet.',
      'users': 'Users',
    },
  };

  String translate(String key, {Map<String, String>? replacements}) {
    final raw = _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']![key] ??
        key;

    if (replacements == null || replacements.isEmpty) {
      return raw;
    }

    var localized = raw;
    replacements.forEach((placeholder, value) {
      localized = localized.replaceAll('{$placeholder}', value);
    });
    return localized;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .any((supported) => supported.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationExtension on BuildContext {
  String t(String key, {Map<String, String>? replacements}) =>
      AppLocalizations.of(this).translate(key, replacements: replacements);
}
